### PR TITLE
Testci

### PR DESCRIPTION
**Pull request by schveiguy**
This should do nothing, and be green. Testing the CI. See #202 conversation.

### CODE REVIEW

**Comment by schveiguy** [comment]
ping @Abscissa see what happens here...

**Comment by Abscissa** [comment]
Ahh, yea, like i thought, this problem has nothing to do with your change or the vibe configuration. Check out lines 206-212 in travis's output. You'll have to expand a folded section to see it. The selected MariaDB version is failing to install. I dont know why travis didnt outright fail right there, or why my ci setup script didnt give a "fail" exit code when it couldnt set up the db. But looks like thats where the problem is.

**Comment by Abscissa** [comment]
I've filed this issue over with travis's new preferred "issue tracker": https://travis-ci.community/t/failures-installing-mariadb-10-2-on-xenial/5284

(Man, I do NOT like that forum software they’re using...)

In the meantime, we need a workaround. It appears that travis's "trusty" architecture doesn't exhibit the problem (go figure - aptly named), but their "xenial" one does. Unfortunately, the "xenial" one seems to be getting used for all new builds (or at least the PRs). I imagine there should be a trivial way to force the use of "trusty", but my brain's about done for the day. So that's the current status.

Oh, and I noticed a couple other problems worth noting:

1. mysqln’s ci-setup script *didn’t* error out the travis job when the DB setup commands it issued failed. (See line 297 here: https://travis-ci.org/mysql-d/mysql-native/jobs/592298238 ) That needs fixed. Fail early FTW.

2. On one job in master, dub fatally complains that `Root package mysql-native references unknown package vibe-d:core` Not sure why only one job in that build dies with that, but in any case, between that and the other message mentioned over at https://github.com/mysql-d/mysql-native/issues/201 , clearly we need to retire vibe-d:core (at least as default) and use `vibe-core`. First thing on this front is to assess the damage (if any) it’ll cause if we just flip the switch (although we can’t check this until the mariadb installation issue is worked around first).

**Comment by schveiguy** [comment]
Should we close this? I think the other PR provides a good enough testing ground for fixing the travis issue.

**Comment by Abscissa** [comment]
> Should we close this? I think the other PR provides a good enough testing ground for fixing the travis issue.

Sounds good.

**Pull request closed without merging**
