### PR TITLE
Use utf8mb4 for the integration test

### PR DESCRIPTION
**Pull request by kubo39**
stop using utf8 for the compatibility problem.

### CODE REVIEW

**Comment by schveiguy** [comment]
This doesn't make sense. It was passing before.

In 10.6 release notes it [says](https://mariadb.com/kb/en/changes-improvements-in-mariadb-106/#character-sets):

> The utf8 character set (and related collations) is now by default an alias for utf8mb3 rather than the other way around. It can be set to imply utf8mb4 by changing the value of the old_mode system variable (MDEV-8334)

Perhaps the fix is to switch to utf8mb3 instead of utf8? Or better yet, use an `OR` clause to select either, and treat the result appropriately.

**Comment by schveiguy** [comment]
I think likely the alias is not stored directly in the database but instead is a protocol feature.

**Comment by kubo39** [comment]
> Perhaps the fix is to switch to utf8mb3 instead of utf8?

First I thought, however, future MySQL release will remove utf8mb3. 
https://dev.mysql.com/doc/refman/8.0/en/charset-unicode-utf8mb3.html

> Or better yet, use an OR clause to select either, and treat the result appropriately.

thx, I'll do that.

**Comment by schveiguy** [comment]
TBH, this test is quite fragile, I wouldn't be sorry to see it be completely refigured.

**Comment by kubo39** [comment]
I found we use MySQL 5.7 and MariaDB10 (10.6, at least now) for the integration test, so I'd use utf8mb4 instead of utf8.

**Comment by schveiguy** [comment]
Thanks!

**Pull request merged**
