### PR TITLE
Add option to use TCP NODELAY

### PR DESCRIPTION
**Pull request by kubo39**

### CODE REVIEW

**Comment by kubo39** [comment]
I've tested by this simple program.

```d
import mysql;
import std;

void main()
{
    const opts = "host=localhost;port=3307;user=testuser;pwd=testpassword;db=testdb";
    auto conn = new Connection(opts);
    scope(exit) conn.close();
    conn.tcpNoDelay(true); // ON or OFF

    while (true)
    {
        auto now = MonoTime.currTime;
        auto rows = conn.query("SELECT 1");
        rows.close();
        writeln(MonoTime.currTime - now);
    }
}
```

## TCP_NODELAY: OFF

```
41 ms, 2 μs, and 8 hnsecs
43 ms, 608 μs, and 8 hnsecs
44 ms, 563 μs, and 7 hnsecs
43 ms, 958 μs, and 2 hnsecs
43 ms, 461 μs, and 4 hnsecs
```

## TCP_NODELAY: ON

```
246 μs and 7 hnsecs
145 μs and 4 hnsecs
119 μs and 5 hnsecs
134 μs and 6 hnsecs
132 μs
```

**Comment by kubo39** [comment]
https://travis-ci.org/github/mysql-d/mysql-native/builds/739545401

**Comment by schveiguy** [comment]
Isn't this achievable with a custom socket creation routine? Note that the `Connection` class can close and reopen sockets at will, so your tcpNoDelay option would go away (not true with a custom routine).

I'm looking at the ctor that takes a socket creation callback.

**Comment by schveiguy** [comment]
I'm tempted to close this. Do you have a response to https://github.com/mysql-d/mysql-native/pull/221#issuecomment-758879149 ?

**Comment by kubo39** [comment]
ok, closing this now.

**Comment by webloft** [comment]
Why is this closed? This is a life safer on remote connections and should be a standard.

**Comment by schveiguy** [comment]
You can achieve the same result with the constructor which accepts a connection setup routine: https://github.com/mysql-d/mysql-native/blob/bbdd562a934bd7d3c456a884ddef75166699b4b5/source/mysql/connection.d#L577-L589

This is far superior, because the connection class can reopen the socket whenever it wants, and it will always call the callback routine, but if you have to do it manually after socket creation, there is no way to check when the socket is recreated.

**Comment by webloft** [comment]
I meant why do you not just add socket flags to the constructor? 

TCP_NODELAY should be enabled as default. You don't need packet efficiency, you need fast queries.

**Comment by schveiguy** [comment]
I don't want to look at mysqlclient source code as it is GPL, but if someone can tell me or show me that that's the default, I'm happy to change it.

This PR though, does it in a way that is prone to errors.

**Comment by webloft** [comment]
I have also no clue about the lib. But the Connector uses it. And yes, it's default there.

**Comment by schveiguy** [comment]
> if someone can tell me or show me that that's the default,

Using mysql command line and strace, I can see the option is being set.

If you want to make a PR that does that by default, I'll accept it.

**Pull request closed without merging**
