### PR TITLE
Prevent segfault on copying ResultRange.

### PR DESCRIPTION
**Pull request by schveiguy**
Simple reproduction:

```D
import mysql;
void main()
{
   ResultRange r1;
   r1 = r1;
}
```

### CODE REVIEW

**Comment by Abscissa** [comment]
Good catch, thanks.

**Comment by schveiguy** [comment]
Can a release happen soon? I'm still using a modified version of mysql-native to work around this issue, and would like to switch to real dub release.

**Comment by Abscissa** [comment]
On September 19, 2017 10:57:54 AM EDT, Steven Schveighoffer <notifications@github.com> wrote:
>Can a release happen soon? I'm still using a modified version of
>mysql-native to work around this issue, and would like to switch to
>real dub release.

Ah, sorry 'bout that. I'm away from the PC right now, but I'll try to remember to tag a release soon as I can.

(I do kinda wish dub was more friendly to non-tagged commits. I realize there's reasons for the way it is, but I find it often translates into a new release for nearly every merged PR or other individual change. Hard to get used to.)

**Comment by schveiguy** [comment]
> I do kinda wish dub was more friendly to non-tagged commits.

I agree. I'm kind of disappointed that they got rid of the ability to depend on specific commits, as that would solve my problem presently without having to resort to having a local copy.

**Comment by schveiguy** [comment]
ping @s-ludwig any thoughts on the last few comments? It's a bit frustrating when you find a bug, your PR is merged, but you have to wait for a release to occur before you can reap the benefits. Especially if you aren't typically working off a custom local copy of the repository.

**Comment by Abscissa** [comment]
Tagged release "v1.1.1"

**Comment by Abscissa** [comment]
FWIW, to any any all who may see: If you need something (even just a tagged release), don't hesitate to ping me, or re-ping, or even straight up harass me about it. I forget things easily, and the squeaky wheel really does get the grease. I have a bad habit of getting caught up in "real life"tm, so if something's really important, make sure to let me know: the worst thing I could possibly do is be busy with other things, so by all means, lemme-have-it.

**Pull request merged**
