### PR TITLE
Added TCP_NODELAY and TCP_KEEPALIVE on default connection

### PR DESCRIPTION
**Pull request by webloft**

### CODE REVIEW

**Comment by schveiguy** [comment]
Thanks, but my thought was actually to just change the default in the socket creation routine, not make a public option to configure it. You can already configure the socket via the callback, I just want the default to be what is expected.

Can you make a PR that just does this?

**Comment by schveiguy** [comment]
I have a few minutes today, I'm just going to implement what I think is the right thing.

**Comment by webloft** [comment]
You mean directly in MySQLSocketPhobos class? I just thought that wouldn't be flexible enough if someone need to create a socket if one just want to disable a feature, for whatever reason.

**Comment by schveiguy** [comment]
Just hang on about 10 minutes, I'm almost done.

**Comment by schveiguy** [comment]
Take a look, this is what I want to do (still working on changelog, then will set up a PR): https://github.com/schveiguy/mysql-native/tree/tcpnodelay

**Comment by webloft** [comment]
OK, then I will close this

**Pull request closed without merging**
