### PR TITLE
Fix #272. Blob types should be accessible via byte[]

### LINKED ISSUE #272: updating from 3.1.0 to 3.2.0 is a breaking change
I was reading the [safe migration guide](https://github.com/mysql-d/mysql-native/blob/master/SAFE_MIGRATION.md) which states that in 3.2.0 the default modules/packages will pull in the unsafe versions of the API to maintain backwards compatibility. 

On updating and doing a build though I got errors:

```
./../../.dub/packages/mysql-native-3.2.0/mysql-native/source/mysql/impl/prepared.d(156,20): Error: none of the overloads of `opAssign` are callable using argument types `(byte[])`, candidates are:
../../../.dub/packages/taggedalgebraic-0.11.22/taggedalgebraic/source/taggedalgebraic/taggedalgebraic.d(147,7):        `taggedalgebraic.taggedalgebraic.TaggedAlgebraic!(_MYTYPE).TaggedAlgebraic.opAssign(TaggedAlgebraic!(_MYTYPE) other)`
../../../.dub/packages/taggedalgebraic-0.11.22/taggedalgebraic/source/taggedalgebraic/taggedalgebraic.d-mixin-140(149,9):        `taggedalgebraic.taggedalgebraic.TaggedAlgebraic!(_MYTYPE).TaggedAlgebraic.opAssign(ubyte[] value)`
../../../.dub/packages/taggedalgebraic-0.11.22/taggedalgebraic/source/taggedalgebraic/taggedalgebraic.d-mixin-140(165,9):        `taggedalgebraic.taggedalgebraic.TaggedAlgebraic!(_MYTYPE).TaggedAlgebraic.opAssign(const(ubyte)[] value)`
../../../.dub/packages/taggedalgebraic-0.11.22/taggedalgebraic/source/taggedalgebraic/taggedalgebraic.d-mixin-140(181,9):        `taggedalgebraic.taggedalgebraic.TaggedAlgebraic!(_MYTYPE).TaggedAlgebraic.opAssign(typeof(null) value)`
../../../.dub/packages/taggedalgebraic-0.11.22/taggedalgebraic/source/taggedalgebraic/taggedalgebraic.d-mixin-140(197,9):        `taggedalgebraic.taggedalgebraic.TaggedAlgebraic!(_MYTYPE).TaggedAlgebraic.opAssign(bool value)`
../../../.dub/packages/mysql-native-3.2.0/mysql-native/source/mysql/impl/prepared.d(156,20):        ... (34 more, -v to show) ...
../../../.dub/packages/mysql-native-3.2.0/mysql-native/source/mysql/impl/prepared.d(327,15): Error: template instance `mysql.impl.prepared.SafePrepared.setArg!(byte[])` error instantiating
source/ddbc/drivers/mysqlddbc.d(705,38):        instantiated from here: `setArg!(byte[])`
```

I tried changing all my imports to be the explicit `mysql.unsafe.*` versions but the error remained the same. For now it seems [ddbc](https://github.com/buggins/ddbc) will need to stay on 3.1.0

ddbc also uses `std.variant` everywhere and potentially could do with some work to use `@safe` code. Not expecting to get time to do that any time soon though

### PR DESCRIPTION
**Pull request by schveiguy**
This should fix the regression in #272

ping @singingbush let me know if this is suitable for your project, or if we need more types to be included.

I haven't tested this yet, so will wait for CI to see if I made any mistakes!

### CODE REVIEW

**Comment by schveiguy** [comment]
ping again @singingbush, any comments? If I don't hear from you for a few days, I'll just merge this and close the issue.

**Comment by SingingBush** [comment]
Sorry been hectic recently. I'll try it out tonight and get back to you

**Comment by SingingBush** [comment]
I've looked through the PR and it seems reasonable but I've not run locally. I noticed that there are now tests for byte[] and ubyte[] so that seems fine. 

I was also trying to get it to work with [std.datetime.systime.SysTime](https://dlang.org/phobos/std_datetime_systime.html#SysTime) as an alternative to [std.datetime.date.DateTime](https://dlang.org/phobos/std_datetime_date.html#.DateTime). SysTime includes timezone which makes it useful if using the timestamp type in MySQL.

According to MySQL docs:
> MySQL converts TIMESTAMP values from the current time zone to UTC for storage, and back from UTC to the current time zone for retrieval. (This does not occur for other types such as DATETIME.) By default, the current time zone for each connection is the server's time. 

So being able to retrieve columns as SysTime would be handy

**Comment by schveiguy** [comment]
> SysTime includes timezone which makes it useful if using the timestamp type in MySQL.

If this is a new feature, and not an already-existing feature, can you open a new issue on it? I want to focus and making sure existing code doesn't break for this release. I agree, returning a SysTime might be useful. We do have a custom mysql Timestamp type, but I admit I never used it.

If it does work in 3.1.0, can you give me an example?

**Comment by schveiguy** [comment]
@SingingBush let me know if there are other problems that need addressing. Will push a new release.

**Pull request merged**
